title: Abrek Koç
author: Abrek
email: abrekkoch@outlook.com
url: https://abrek-koc.github.io
baseurl: "/" 
description: > # text 
  <p>Localization/Automation Engineer, reads and writes about NLP, computational linguistics, and fun stuff. Currently working on networking and DevOps.</p>
  <p>Hit me up for a chat around video games, gastronomy and engineering.</p>
permalink: /:slug.html

favicon: "favicon.png" 

remote_theme: riggraz/no-style-please 

theme_config:
  appearance: "auto" # "light", "dark" or "auto"
  back_home_text: ".." 
  date_format: "%Y-%m-%d" 
  show_description: true

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
